version: '3.0'

services:
  backoffice:
    depends_on:
      - proxy
    image: zenika/marcel-backoffice:dev
    labels:
      traefik.backend: backoffice
      traefik.frontend.rule: "PathPrefix: /"
    volumes:
      - ./backoffice:/usr/share/nginx/html/conf:ro

  frontend:
    depends_on:
      - proxy
    image: zenika/marcel-frontend:dev
    labels:
      traefik.backend: frontend
      traefik.frontend.rule: "PathPrefixStrip: /front/"
    volumes:
      - ./frontend:/usr/share/nginx/html/conf:ro

  api:
    depends_on:
      - proxy
    image: zenika/marcel:dev
    command: ["api"]
    labels:
      traefik.backend: api
      traefik.frontend.rule: "PathPrefix: /api/v1/"
    volumes:
      - ./config.json:/etc/marcel/config.json:ro
      - ./api/data:/var/lib/marcel/data
      - ./api/plugins:/var/lib/marcel/plugins
      - ./api/medias:/var/lib/marcel/medias

  proxy:
    command: --web --docker --logLevel=DEBUG
    image: traefik
    ports:
      - 80:80/tcp
      - 8080:8080/tcp
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /dev/null:/traefik.toml
