defaults: &defaults
  working_directory: /tmp
  docker:
    - image: circleci/buildpack-deps:stable-curl

version: 2
jobs:
  debug_node:
    docker:
      - image: circleci/node:12
    steps:
      - run: node --version
      - run: yarn --version

  debug_go:
    docker:
      - image: circleci/golang:1.12
    steps:
      - run: go version

  build_backoffice:
    <<: *defaults
    docker:
      - image: circleci/node:12
    working_directory: /home/circleci/app
    steps:
      - checkout
      - restore_cache:
          keys:
            - backoffice-deps-{{ checksum "backoffice/package.json" }}
      - run:
          command: yarn
          working_directory: backoffice
      - save_cache:
          paths:
            - backoffice/node_modules
          key: backoffice-deps-{{ checksum "backoffice/package.json" }}
      - run:
          command: yarn build
          working_directory: backoffice
      - persist_to_workspace:
          root: .
          paths:
            - backoffice/build

  build_frontend:
    <<: *defaults
    docker:
      - image: circleci/node:12
    working_directory: /home/circleci/app
    steps:
      - checkout
      - restore_cache:
          keys:
            - frontend-deps-{{ checksum "frontend/package.json" }}
      - run:
          command: yarn
          working_directory: frontend
      - save_cache:
          paths:
            - frontend/node_modules
          key: frontend-deps-{{ checksum "frontend/package.json" }}
      - run:
          command: yarn build
          working_directory: frontend
      - persist_to_workspace:
          root: .
          paths:
            - frontend/build

  build_marcel:
    <<: *defaults
    working_directory: /go/app
    docker:
      - image: circleci/golang:1.12
    steps:
      - checkout
      - restore_cache:
          key: marcel-deps-{{ checksum "go.mod" }}
      - run: go mod download
      - save_cache:
          key: marcel-deps-{{ checksum "go.mod" }}
          paths:
            - /go/pkg/mod
      - run: go test .
      - run: CGO_ENABLED=0 go build -ldflags '-extldflags "-static"' -tags 'osusergo netgo' -o marcel
      - persist_to_workspace:
          root: .
          paths:
            - Dockerfile
            - marcel

  docker_build_backoffice:
    <<: *defaults
    docker:
      - image: circleci/buildpack-deps:stable-curl
    working_directory: /tmp/app
    steps:
      - checkout
      - setup_remote_docker
      - attach_workspace:
          at: /tmp/app
      - run:
          command: ${CIRCLE_WORKING_DIRECTORY}/scripts/docker_build.sh zenika/marcel-backoffice
          working_directory: backoffice

  docker_build_frontend:
    <<: *defaults
    docker:
      - image: circleci/buildpack-deps:stable-curl
    working_directory: /tmp/app
    steps:
      - checkout
      - setup_remote_docker
      - attach_workspace:
          at: /tmp/app
      - run:
          command: ${CIRCLE_WORKING_DIRECTORY}/scripts/docker_build.sh zenika/marcel-frontend
          working_directory: frontend

  docker_build_marcel:
    <<: *defaults
    docker:
      - image: circleci/buildpack-deps:stable-curl
    working_directory: /tmp/app
    steps:
      - checkout
      - setup_remote_docker
      - attach_workspace:
          at: /tmp/app
      - run: ${CIRCLE_WORKING_DIRECTORY}/scripts/docker_build.sh zenika/marcel

  deploy_integration:
    docker:
      - image: google/cloud-sdk:latest
    steps:
      - checkout
      - restore_cache:
          keys:
            - plugins-package-{{ .Revision }}
      - run: ./scripts/install.sh
      - run:
          command: rm -rf ${HOME}/.ssh
          when: always
      - run:
          command: rm -f ${HOME}/gcloud-service-key.json
          when: always

filters-all: &filters-all
  tags:
    only: /.*/
filters-master: &filters-master
  branches:
    only:
      - master

workflows:
  version: 2
  build:
    jobs:
      - debug_node:
          filters: *filters-all
      - debug_go:
          filters: *filters-all
      - build_backoffice:
          filters: *filters-all
      - build_frontend:
          filters: *filters-all
      - build_marcel:
          filters: *filters-all
      - docker_build_backoffice:
          filters: *filters-all
          requires:
            - build_backoffice
      - docker_build_frontend:
          filters: *filters-all
          requires:
            - build_frontend
      - docker_build_marcel:
          filters: *filters-all
          requires:
            - build_marcel
      - deploy_integration:
          filters: *filters-master
          requires:
            - docker_build_marcel
            - docker_build_backoffice
            - docker_build_frontend
