defaults: &defaults
  working_directory: /tmp
  docker:
    - image: circleci/buildpack-deps:stable-curl

version: 2
jobs:
  debug_node:
    docker:
      - image: circleci/node:12
    steps:
      - run: node --version
      - run: yarn --version

  debug_go:
    docker:
      - image: circleci/golang:1.12
    steps:
      - run: go version

  build_backoffice:
    docker:
      - image: circleci/node:12
    steps:
      - checkout
      - restore_cache:
          keys:
          - backoffice-dependencies-{{ checksum "back-office/package.json" }}
          - backoffice-dependencies-
      - run:
          command: yarn
          working_directory: back-office
      - save_cache:
          paths:
            - back-office/node_modules
          key: backoffice-dependencies-{{ checksum "back-office/package.json" }}
      - run:
          command: yarn build
          working_directory: back-office
      - save_cache:
          paths:
            - back-office/build
          key: backoffice-build-{{ .Revision }}

  build_frontend:
    docker:
      - image: circleci/node:12
    steps:
      - checkout
      - restore_cache:
          keys:
          - frontend-dependencies-{{ checksum "frontend/package.json" }}
          - frontend-dependencies-
      - run:
          command: yarn
          working_directory: frontend
      - save_cache:
          paths:
            - frontend/node_modules
          key: frontend-dependencies-{{ checksum "frontend/package.json" }}
      - run:
          command: yarn build
          working_directory: frontend
      - save_cache:
          paths:
            - frontend/build
          key: frontend-build-{{ .Revision }}


  build_marcel:
    <<: *defaults
    working_directory: /go/app
    docker:
      - image: circleci/golang:1.12
    steps:
      - checkout
      - restore_cache:
          key: marcel-deps-{{ checksum "go.mod" }}
      - run: go mod download
      - save_cache:
          key: marcel-deps-{{ checksum "go.mod" }}
          paths:
            - /go/pkg/mod
      - run: go test .
      - run: CGO_ENABLED=0 go build -ldflags '-extldflags "-static"' -tags 'osusergo netgo' -o marcel
      - persist_to_workspace:
          root: .
          paths:
            - Dockerfile
            - marcel

  package_plugins:
    docker:
      - image: circleci/buildpack-deps:stable-scm
    steps:
      - checkout
      - run: git submodule sync
      - run: git submodule update --init
      - run: tar -czf plugins.tar.gz plugins
      - save_cache:
          paths:
            - plugins.tar.gz
          key: plugins-package-{{ .Revision }}

  docker_build_marcel:
    <<: *defaults
    working_directory: /tmp/app
    docker:
      - image: circleci/buildpack-deps:stable-curl
    steps:
      - setup_remote_docker
      - attach_workspace:
          at: /tmp/app
      - run: docker build -t zenika/marcel:dev .
      - run: docker login -u $DOCKER_LOGIN -p $DOCKER_PASSWORD
      - run: docker push zenika/marcel:dev

  docker_build_backoffice:
    docker:
      - image: circleci/buildpack-deps:stable-curl
    steps:
      - checkout
      - setup_remote_docker
      - restore_cache:
          keys:
            - backoffice-build-{{ .Revision }}
      - run:
          command: docker build -t zenika/marcel-backoffice:dev .
          working_directory: back-office
      - run: docker login -u $DOCKER_LOGIN -p $DOCKER_PASSWORD
      - run: docker push zenika/marcel-backoffice:dev

  docker_build_frontend:
    docker:
      - image: circleci/buildpack-deps:stable-curl
    steps:
      - checkout
      - setup_remote_docker
      - restore_cache:
          keys:
            - frontend-build-{{ .Revision }}
      - run:
          command: docker build -t zenika/marcel-frontend:dev .
          working_directory: frontend
      - run: docker login -u $DOCKER_LOGIN -p $DOCKER_PASSWORD
      - run: docker push zenika/marcel-frontend:dev

  deploy_integration:
    docker:
      - image: circleci/buildpack-deps:stable-curl
    steps:
      - checkout
      - restore_cache:
          keys:
            - plugins-package-{{ .Revision }}
      - run: echo $INTEGRATION_SERVER_KEY | sed s/retourligne/\\n/g > integration_key.pem
      - run: chmod 400 integration_key.pem
      - run: scp -o StrictHostKeyChecking=no -i integration_key.pem plugins.tar.gz docker-compose.yml ubuntu@35.158.222.144:~/
      - run: ssh -o StrictHostKeyChecking=no -i integration_key.pem ubuntu@35.158.222.144 "./MARCEL/deploy.sh"
      - run: rm -f integration_key.pem

workflows:
  version: 2
  build:
    jobs:
       - debug_node
       - debug_go
       - build_backoffice
       - build_frontend
       - build_marcel
          # requires:
          #   - build_backoffice
          #   - build_frontend
       - package_plugins
       - docker_build_backoffice:
          requires:
            - build_backoffice
       - docker_build_frontend:
          requires:
            - build_frontend
       - docker_build_marcel:
          requires:
            - build_marcel
       - deploy_integration:
          requires:
            - docker_build_marcel
            - docker_build_backoffice
            - docker_build_frontend
            - package_plugins
          filters:
            branches:
              only:
                - master
